fixing gitfight

diff --git a/gitfight/gitfight b/gitfight/gitfight
--- a/gitfight/gitfight
+++ b/gitfight/gitfight
@@ -72,29 +72,31 @@ function calculateScores {
   opponentScore=100
   myScore=100
   while read line; do
-    myLine=`echo "$line" | grep "$me"`
-    opponentLine=`echo "$line" | grep "$opponent"`
-    if ! [ -z "$myLine" ]; then
-      # my lines log the damage done to opponent
-      hit=`echo "$line" | cut -d, -f4 | cut -d" " -f1`
-      damage=`echo "$line" | cut -d"," -f4 | cut -d" " -f2`
-      if [ "$hit" = "HIT" ]; then
-        opponentScore=`expr $opponentScore - $damage`
+    if ! [ -z "$line" ]; then
+      myLine=`echo "$line" | grep "$me"`
+      opponentLine=`echo "$line" | grep "$opponent"`
+      if ! [ -z "$myLine" ]; then
+        # my lines log the damage done to opponent
+        hit=`echo "$line" | cut -d, -f4 | cut -d" " -f1`
+        damage=`echo "$line" | cut -d"," -f4 | cut -d" " -f2`
+        if [ "$hit" = "HIT" ]; then
+          opponentScore=`expr $opponentScore - $damage`
+        fi
+      elif ! [ -z "$opponentLine" ]; then
+        # opponent lines log the damage done to myself
+        hit=`echo "$line" | cut -d, -f4 | cut -d" " -f1`
+        damage=`echo "$line" | cut -d"," -f4 | cut -d" " -f2`
+        if [ "$hit" = "HIT" ]; then
+          myScore=`expr $myScore - $damage`
+        fi
+      else
+        echo
+        echo "There was an error processing the git log."
+        echo
+        exit
       fi
-    elif ! [ -z "$opponentLine" ]; then
-      # opponent lines log the damage done to myself
-      hit=`echo "$line" | cut -d, -f4 | cut -d" " -f1`
-      damage=`echo "$line" | cut -d"," -f4 | cut -d" " -f2`
-      if [ "$hit" = "HIT" ]; then
-        myScore=`expr $myScore - $damage`
-      fi
-    else
-      echo
-      echo "gitwar.log has incorrect syntax!"
-      echo
-      exit
     fi
-  done < <( sed 1d "$logfile" )
+  done < <( echo "$log" )
 }
 
 function checkGameOver {
@@ -121,7 +123,7 @@ function checkGameOver {
 }
 
 function printRound {
-  round=`cat "$logfile" | wc -l`
+  round=`echo "$log" | wc -l`
   round=`expr "$round" / 2 + "$round" % 2`
   if [[ "$myScore" -ge "0" && "$opponentScore" -ge "0" ]]; then
     echo "[ROUND $round]"
@@ -134,7 +136,7 @@ function printRound {
 }
 
 function getRecentEvent {
-  opponentMove=`tail -1 gitwar.log`
+  opponentMove=`../gitwar -l -tail`
   checkOpponent=`echo "$opponentMove" | cut -d, -f2`
   action=`echo "$opponentMove" | cut -d, -f3`
   article="a"
@@ -186,15 +188,14 @@ function loop {
     echo
 
     performAttack $attack
-    echo "`date "+%Y-%m-%d %H:%M:%S %z"`,$me,$attack,$attackResult" >> gitwar.log
+    echo "`date "+%b %d %Y:"` $recentEvent" >> gitwar.log
     echo
-
-
 
     # Call gitwar to give opponent a turn
     getRecentEvent
     checkGameOver
     ../gitwar "$recentEvent"
+    log=`../gitwar -l`
 
     echo
   done
@@ -208,8 +209,7 @@ echo
 echo -n "[GITFIGHT!] "
 
 # Initialize some stuff
-logfile="gitwar.log"
-log=`cat gitwar.log`
+log=`../gitwar -l`
 me=`git config "user.name"`
 users=`cat gitwar.users`
 
@@ -237,13 +237,14 @@ printRound
 echo "Welcome back $me!"
 echo
 
-justWent=`tail -1 gitwar.log | grep $me`
+justWent=`../gitwar -l -tail | grep $me`
 
 if ! [ -z "$justWent" ]; then
   echo "Looks like it's not your turn. Please wait for your opponent to attack..."
   echo
   # Call gitwar to wait for opponent
   ../gitwar -w
+  log=`../gitwar -l`
 
   echo
 
@@ -263,13 +264,14 @@ else
   echo
 
   performAttack $attack
-  echo "`date "+%Y-%m-%d %H:%M:%S %z"`,$me,$attack,$attackResult" >> gitwar.log
+  echo "`date "+%b %d %Y:"` $recentEvent" >> gitwar.log
   echo
 
   # Call gitwar to give opponent a turn
   getRecentEvent
   checkGameOver
   ../gitwar "$recentEvent"
+  log=`../gitwar -l`
 
   echo
 
